apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: canary-restricted
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: restricted-apps
  source:
    path: .
    repoURL: https://github.com/idan-codefresh/canary-rollout.git
    targetRevision: HEAD
  destination:
    name: in-cluster
    namespace: apps
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
